# Generated by Django 4.2.4 on 2023-08-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctortimeslot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorTimeSlot',
        ),
    ]
