# Generated by Django 4.2.4 on 2023-08-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctortimeslot', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctortimeslot',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='doctortimeslot',
            name='updated_on',
        ),
    ]
